alias ll='ls -l'
alias la='ls -A'
alias al='ls -A'
alias l='ls -lah'

alias g='git'
alias s='git status -sb'
alias gl='git log --oneline'
alias lg='git log --oneline'
alias a='git add'
alias aa='git add --all'
alias ci='git commit -m'
alias ic='git commit -m'
alias d='git diff'
alias dc='git diff --cached'
alias sw='git switch'
alias swc='git switch -c'
alias p='git push'
alias pl='git pull'
alias f='git fetch --prune'
alias ciaclean='git branch --merged origin/main | grep -vE "^\s*(\*|main|develop)" | xargs -n 1 git branch -d'

alias o='open'

alias sus='systemctl suspend'
